services:
  - type: web
    name: ocr-pdf-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1
